In [70]:
from dgl.data import citation_graph,CoraDataset,TUDataset,GINDataset, ICEWS18
import torch
from torch import nn
from dgl import DGLGraph
import numpy as np
import dgl
from datasets.prepocessing import one_class_processing

In [3]:
torch.cuda.is_available()

False

In [ ]:
data =citation_graph.load_cora()
#data =citation_graph.load_citeseer()
#data =TUDataset('PROTEINS_full')
#data =ICEWS18('train')

In [179]:
def pre_process(args,dataset):

    for i in range(len(dataset)):
        print(i)
        #dataset.graph_lists[i].ndata
        normal_idx=torch.where(dataset.graph_lists[i].ndata['node_labels']==0)[0]
        abnormal_idx=torch.where(dataset.graph_lists[i].ndata['node_labels']!=0)[0]
        dataset.graph_lists[i].ndata['node_labels'][normal_idx]=0
        dataset.graph_lists[i].ndata['node_labels'][abnormal_idx]=1
        
        g=dgl.transform.add_self_loop(dataset.graph_lists[i])
        g.ndata.update(dataset.graph_lists[i].ndata)
        dataset.graph_lists[i]=g
        print(dataset.graph_lists[i].ndata['node_labels'].max())
        #print(dataset.graph_lists[i])
    return dataset

In [180]:
from dgl.data import tu
dataset = tu.TUDataset(name='ENZYMES')
print(len(dataset))
train_size = int(0.6 * len(dataset))
test_size = int(0.2 * len(dataset))
val_size = int(len(dataset) - train_size - test_size)
dataset = pre_process(None,dataset)
dataset_train, dataset_val, dataset_test = torch.utils.data.random_split(
    dataset, (train_size, val_size, test_size))

600
0
tensor(1)


In [187]:
batch_graph.ndata['node_attr'].size()

torch.Size([998, 29])

In [198]:
normlizing = nn.BatchNorm1d(batch_graph.ndata['node_attr'].shape[1], affine=False)
normlizing

BatchNorm1d(29, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)

In [199]:
input_attr=normlizing(batch_graph.ndata['node_attr'].unsqueeze(1))
input_attr.squeeze().size()

RuntimeError: running_mean should contain 1 elements not 29

In [193]:
input_attr.s

tensor([[[-0.2124, -0.1740, -0.3083,  ..., -0.3659,  2.1478, -0.3659]],

        [[ 0.5671,  0.6050, -0.3623,  ..., -0.4192,  2.0655, -0.4192]],

        [[ 0.5936,  0.8622, -0.2124,  ..., -0.5003,  2.0136, -0.5003]],

        ...,

        [[ 2.3031,  2.4176, -0.3475,  ..., -0.4784,  1.4195, -0.4784]],

        [[ 0.1285,  0.1709, -0.3163,  ..., -0.3798,  2.0772, -0.3798]],

        [[ 2.4303,  2.4776, -0.3945,  ..., -0.4576,  1.3729, -0.4576]]])

In [195]:
batch_graph.ndata['node_attr']

tensor([[  8.,  10.,   3.,  ...,   0., 131.,   0.],
        [ 52.,  54.,   3.,  ...,   0., 131.,   0.],
        [ 57.,  71.,  15.,  ...,   0., 131.,   0.],
        ...,
        [170., 177.,   8.,  ...,   0., 116.,   0.],
        [ 24.,  26.,   3.,  ...,   0., 116.,   0.],
        [183., 186.,   4.,  ...,   0., 116.,   0.]])

In [150]:
c=torch.ones(32)
x=torch.ones(50,32)+10
print(x)
print(c)

tensor([[11., 11., 11.,  ..., 11., 11., 11.],
        [11., 11., 11.,  ..., 11., 11., 11.],
        [11., 11., 11.,  ..., 11., 11., 11.],
        ...,
        [11., 11., 11.,  ..., 11., 11., 11.],
        [11., 11., 11.,  ..., 11., 11., 11.],
        [11., 11., 11.,  ..., 11., 11., 11.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [151]:
t=(x - c)** 2
t.size()

torch.Size([50, 32])

In [152]:
dist1 = torch.sum((x - c) ** 2, dim=1)
print(dist1.size())
dist1

torch.Size([50])


tensor([3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200.,
        3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200.,
        3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200.,
        3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200.,
        3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200., 3200.])

In [153]:
torch.mean(dist1)

tensor(3200.)

In [154]:
c_=c.repeat(x.size()[0],1)
# # print('c',c.size())
res=x-c_
# # print('res',res.size())
res=torch.mean(res, 1, keepdim=True)
# # print('res mean',res.size())
dist2=torch.diag(torch.mm(res,torch.transpose(res, 0, 1)))
print(dist2.size())
dist2

torch.Size([50])


tensor([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        100., 100.])

In [155]:
torch.mean(dist2)

tensor(100.)

In [36]:
torch.where(dataset.graph_lists[0].ndata['node_labels']==0)[0]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21])

In [10]:
def batching_graph(batch):
    '''
    for dataset batching
    transform ndata to tensor (in gpu is available)
    '''
    graphs, labels = map(list, zip(*batch))
    #cuda = torch.cuda.is_available()

    # batch graphs and cast to PyTorch tensor
    for graph in graphs:
        for (key, value) in graph.ndata.items():
            graph.ndata[key] = value.float()
    batched_graphs = dgl.batch(graphs)

    # cast to PyTorch tensor
    batched_labels = torch.LongTensor(np.array(labels))

    return batched_graphs, batched_labels

In [43]:
train_loader=torch.utils.data.DataLoader(dataset_train,
                                       batch_size=32,
                                       shuffle=True,
                                       collate_fn=batching_graph,
                                       drop_last=True,
                                       num_workers=4)

In [156]:
for (batch_idx, (batch_graph, graph_labels)) in enumerate(train_loader):
    print(batch_idx)
    if batch_idx >3:
        break

0
1
2
3
4


In [74]:
a=batch_graph.ndata['node_attr']
m = nn.BatchNorm1d(29, affine=False)

In [79]:
batch_graph.ndata['node_attr'].shape[1]

29

In [172]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [174]:
b=np.append(a,None)
b

array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, None],
      dtype=object)

In [76]:
output.max()

tensor(16.6918)

In [34]:
normal_idx=torch.where(batch_graph.ndata['node_labels']==0)[0]
abnormal_idx=torch.where(batch_graph.ndata['node_labels']!=0)[0]


normal_idx

tensor([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          24,   25,   38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
          48,   49,   50,   51,   52,   53,   54,   55,   56,   57,   71,   78,
          79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
          91,   92,  135,  136,  137,  138,  139,  140,  141,  142,  143,  144,
         145,  175,  176,  177,  178,  179,  180,  181,  182,  183,  184,  185,
         186,  187,  197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
         207,  208,  209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
         219,  220,  221,  222,  223,  224,  225,  226,  227,  228,  229,  230,
         261,  262,  263,  264,  265,  266,  271,  272,  273,  274,  305,  306,
         307,  308,  309,  310,  311,  312,  313,  314,  315,  332,  333,  334,
         335,  336,  343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
         353,  354,  355,  356,  357,  3

In [29]:
batch_graph.ndata['node_labels'][normal_idx]=0
batch_graph.ndata['node_labels'][abnormal_idx]=1

In [32]:
batch_graph.ndata['node_labels'].sum()

tensor(593.)

In [ ]:
input_dim, label_dim, max_num_node = dataset.statistics()

In [ ]:
print(len(dataset_train))
print(len(dataset_val))
print(len(dataset_test))

In [ ]:
label0=data[0][0].ndata['node_labels']
label1=data[1][0].ndata['node_labels']
label2=data[2][0].ndata['node_labels']

In [ ]:
label1

In [ ]:
print(len(label0))
print(len(label1))
print(len(label2))

In [ ]:
data[1][0].ndata['node_labels'].size()

In [ ]:
labels,train_mask,val_mask,test_mask=one_class_processing(data[0][0],4)

In [ ]:
from collections import Counter
Counter(data.labels)

In [ ]:
normal_class=2
labels,train_mask,val_mask,test_mask=one_class_processing(data.labels,normal_class)

In [ ]:
labels[train_mask.astype(int)].shape

In [ ]:
print('train',np.sum(labels[train_mask.astype(int)==1]))
print('val',np.sum(labels[val_mask.astype(int)==1]))
print('test',np.sum(labels[test_mask.astype(int)==1]))

In [ ]:
print('train',np.sum(train_mask))
print('val',np.sum(val_mask))
print('test',np.sum(test_mask))

In [ ]:
train_mask.shape